Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -61,13 +61,13 @@ jobs:
     - name: Test
       run: dotnet test src/MyFirstProject.Tests/MyFirstProject.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --verbosity normal --logger "trx;LogFileName=test-results.trx"
 
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()
-      with:
-        name: UnitTests
-        path: src/MyFirstProject.Tests/TestResults/*.trx
-        reporter: dotnet-trx
+    #- name: Test Report
+    #  uses: dorny/test-reporter@v1
+    #  if: success() || failure()
+    #  with:
+    #    name: UnitTests
+    #    path: src/MyFirstProject.Tests/TestResults/*.trx
+    #    reporter: dotnet-trx
         
     - name: Publish APP
       run: dotnet publish src/MyFirstProject.WebApp/MyFirstProject.WebApp.csproj --no-build --configuration ${{ env.CONFIGURATION }} --output PublishApp
